name: example_mint
description: An example app for mintminter_mint package.
publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mintminter_mint:
    path: ../../mint

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
