name: mintminter_mint
description: A Flutter package - Common views, utils and extensions for MintMinter app
homepage: https://github.com/m11v/mint
repository: https://github.com/m11v/mint

version: 2.7.1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  url_launcher: ^6.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dartx: ^1.2.0
  html: ^0.15.5
  dio: ^5.8.0+1
  flutter_bloc: ^9.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.4
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  assets:
    - assets/images/
