name: mint
description: Common views & Utils for MintMinter app
version: 1.0.0
homepage: https://github.com/m11v/mint
repository: https://github.com/m11v/mint

environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
