name: mintminter_mint
description: A Flutter package - Common views, utils and extensions for MintMinter app
homepage: https://github.com/m11v/mint
repository: https://github.com/m11v/mint

version: 1.0.5

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^3.1.0
  equatable: ^2.0.5
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/