name: mintminter_mint
description: A Flutter package - Common views, utils and extensions for MintMinter app
homepage: https://github.com/m11v/mint
repository: https://github.com/m11v/mint

version: 2.5.5

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  url_launcher: ^6.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dartx: ^1.2.0
  html: ^0.15.4
  dio: ^5.3.3
  flutter_bloc: ^8.1.3
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/
