name: Mint Main

on:
  push:
    branches: [ "main" ]
    paths:
      - "!example_mint/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "!example_mint/**"

jobs:
  build-mint:
    defaults:
      run:
        working-directory: ./  
         
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze

      - name: Run unit tests
        run: flutter test
